// Generates a VAPID key pair and appends it to .env.local. The PRIVATE key is never printed.
// Usage: node scripts/generate-vapid.mjs
import webpush from "web-push";
import { appendFileSync, existsSync, readFileSync } from "node:fs";

const file = ".env.local";
const current = existsSync(file) ? readFileSync(file, "utf8") : "";
if (/^VAPID_PRIVATE_KEY=/m.test(current)) {
  console.log("VAPID keys already exist in .env.local. Nothing changed.");
  process.exit(0);
}
const keys = webpush.generateVAPIDKeys();
appendFileSync(
  file,
  `\n# Web Push (generated by scripts/generate-vapid.mjs). The private key is SECRET: add it to Vercel too.\n` +
    `NEXT_PUBLIC_VAPID_PUBLIC_KEY=${keys.publicKey}\n` +
    `VAPID_PRIVATE_KEY=${keys.privateKey}\n` +
    `# Contact sent to push services. Replace with a real mailto: address or your https:// site URL.\n` +
    `VAPID_SUBJECT=mailto:owner@kabash.example\n`,
);
console.log("VAPID keys written to .env.local (public key length %d). The private key was not printed.", keys.publicKey.length);
